import { NgModule } from '@angular/core';
import {
	MatFormFieldModule,
	MatAutocompleteModule,
	MatButtonToggleModule,
	MatCardModule,
	MatCheckboxModule,
	MatDatepickerModule,
	MatDialogModule,
	MatDividerModule,
	MatExpansionModule,
	MatGridListModule,
	MatIconModule,
	MatInputModule,
	MatListModule,
	MatMenuModule,
	MatNativeDateModule,
	MatPaginatorModule,
	MatProgressBarModule,
	MatProgressSpinnerModule,
	MatRadioModule,
	MatRippleModule,
	MatSelectModule,
	MatSidenavModule,
	MatSliderModule,
	MatSlideToggleModule,
	MatSnackBarModule,
	MatSortModule,
	MatStepperModule,
	MatTableModule,
	MatTabsModule,
	MatToolbarModule,
	MatTooltipModule,
	MatButtonModule,
	MatChipsModule,
} from '@angular/material';
// import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { FlexLayoutModule } from '@angular/flex-layout';
import { ScrollingModule } from '@angular/cdk/scrolling';
import { SpinnerComponent } from './spinner/spinner.component';
import { ToolBarComponent } from './tool-bar/tool-bar.component';
import { CommonModule } from '@angular/common';

// @ts-ignore
@NgModule({
	imports: [
		MatDialogModule,
		MatFormFieldModule,
		MatInputModule,
		MatGridListModule,
		MatSelectModule,
		MatIconModule,
		MatCheckboxModule,
		FlexLayoutModule,
		MatRadioModule,
		MatCardModule,
		MatAutocompleteModule,
		MatButtonToggleModule,
		MatCardModule,
		MatCheckboxModule,
		MatStepperModule,
		MatDatepickerModule,
		MatDialogModule,
		MatDividerModule,
		MatExpansionModule,
		MatGridListModule,
		MatIconModule,
		MatInputModule,
		MatListModule,
		MatMenuModule,
		MatNativeDateModule,
		MatProgressBarModule,
		MatProgressSpinnerModule,
		MatRadioModule,
		MatRippleModule,
		MatSelectModule,
		MatSidenavModule,
		MatSliderModule,
		MatSlideToggleModule,
		MatSnackBarModule,
		MatSortModule,
		MatTableModule,
		MatTabsModule,
		MatToolbarModule,
		MatTooltipModule,
		MatButtonModule,
		MatRadioModule,
		MatListModule,
		MatPaginatorModule,
		ScrollingModule,
		CommonModule,
	],
	exports: [
		MatDialogModule,
		MatFormFieldModule,
		MatInputModule,
		MatGridListModule,
		MatSelectModule,
		MatIconModule,
		MatCheckboxModule,
		FlexLayoutModule,
		MatRadioModule,
		MatCardModule,
		MatAutocompleteModule,
		MatButtonToggleModule,
		MatCardModule,
		MatChipsModule,
		MatCheckboxModule,
		MatStepperModule,
		MatDatepickerModule,
		MatDialogModule,
		MatDividerModule,
		MatExpansionModule,
		MatGridListModule,
		MatIconModule,
		MatInputModule,
		MatListModule,
		MatMenuModule,
		MatNativeDateModule,
		MatPaginatorModule,
		MatProgressBarModule,
		MatProgressSpinnerModule,
		MatRadioModule,
		MatRippleModule,
		MatSelectModule,
		MatSidenavModule,
		MatSliderModule,
		MatSlideToggleModule,
		MatSnackBarModule,
		MatSortModule,
		MatTableModule,
		MatTabsModule,
		MatToolbarModule,
		MatTooltipModule,
		MatButtonModule,
		MatRadioModule,
		MatListModule,
		ScrollingModule,
		SpinnerComponent,
	],
	declarations: [SpinnerComponent],
})
export class MaterialModule {}
